language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
- pypy3
install:
- pip install -r requirements.txt
- pip install myql coverage coveralls pytest
script:
- coverage run --source=yahoo_oauth -m pytest -v tests.py
before_install:
- openssl aes-256-cbc -K $encrypted_203a34dfdebf_key -iv $encrypted_203a34dfdebf_iv
  -in secrets.tar.enc -out secrets.tar -d
after_success:
- coverage report
- coveralls
